[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"  # Must match your directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000
  functions = "netlify/functions"